name: U.S. Criminal Records Agency
favicon: null
layout_spectrum: 0.14257
typography_spectrum: 0.00546
title: Information that can help save your life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#9f9f9f'
    - '#616161'
    - '#c9c9c9'
  brandStrength: 0.3894306421279907
  lightness: 0.9692446629051119
  saturation: 0.9996930893976241
  rhythmicContrast: 0.5
purpose: []
