name: U.S. Criminal Records Agency
favicon: null
layout_spectrum: 0.03876395826227963
typography_spectrum: 0.3791081083472818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3894306421279907
  lightness: 0.9692446629051119
  saturation: 0.9996930893976241
  rhythmicContrast: 0.414933938998729
purpose: []
